/**
 * Defines an interactive implementation of all non-deterministic primitive
 * value calls. Data is generated by prompting the user.
 * @date 2019
 */

#include "verify.h"

#include <stdio.h>

void on_entry(const char* _type, const char* _msg)
{
    printf("%s [%s]: ", _msg, _type);
}

int8_t nd_int8_t(const char* _msg)
{
    on_entry(_msg, "int8");
    int8_t retval;
    scanf("%hhd", &retval);
    return retval;
}

int16_t nd_int16_t(const char* _msg)
{
    on_entry(_msg, "int16");
    int16_t retval;
    scanf("%hd", &retval);
    return retval;
}

int32_t nd_int32_t(const char* _msg)
{
    on_entry(_msg, "int32");
    int32_t retval;
    scanf("%d", &retval);
    return retval;
}

int64_t nd_int64_t(const char* _msg)
{
    on_entry(_msg, "int64");
    int64_t retval;
    scanf("%ld", &retval);
    return retval;
}

uint8_t nd_uint8_t(const char* _msg)
{
    on_entry(_msg, "uint8");
    uint8_t retval;
    scanf("%hhd", &retval);
    return retval;
}

uint16_t nd_uint16_t(const char* _msg)
{
    on_entry(_msg, "uint16");
    uint16_t retval;
    scanf("%hd", &retval);
    return retval;
}

uint32_t nd_uint32_t(const char* _msg)
{
    on_entry(_msg, "uint32");
    uint32_t retval;
    scanf("%d", &retval);
    return retval;
}

uint64_t nd_uint64_t(const char* _msg)
{
    on_entry(_msg, "uint64");
    uint64_t retval;
    scanf("%ld", &retval);
    return retval;
}
